language: php

sudo: false

php:
  - 5.5

env:
	global:
		- DEFAULT = 1

matrix:
	fast_finish: true

install:
	- composer self-update
	- composer install --prefer-dist --no-interaction --dev

before_script:
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - sh -c "composer require --dev satooshi/php-coveralls:1.*; fi"
  - sh -c "mkdir -p build/logs; fi"

script:
	- sh -c "phpunit --stderr; fi"
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config ./webroot"
  - sh -c "phpunit --stderr --coverage-clover build/logs/clover.xml; fi"
  - sh -c "php vendor/bin/coveralls -c .coveralls.yml -v; fi"

notifications:
  email: false
